Pycharm/Dasmach/Dasmach/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('buysale.urls')),
]

Pycharm/Dasmach/buysale/urls.py
from django.conf.urls import url, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^vup/', views.vup, name = 'vup'),
    url(r'^catalogue/', views.catalogue, name = 'catalogue'),
    url(r'^single/', views.single, name = 'single'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Pycharm/Dasmach/buysale/models.py
from django.db import models


# Create your models here.
class newsletter(models.Model):
    newsletter_email = models.EmailField(max_length=200)

class contact (models.Model):
    contact_name = models.CharField(max_length=50)
    contact_email = models.EmailField(max_length=80)
    contact_mobile = models.CharField(max_length=10)
    contact_message = models.TextField(max_length=200)

class car(models.Model):
    # Drop Down settings
    # mfg_year
    MFG_YR = [
        ('', 'Year'),
        ('1', '2018'),
        ('2', '2017'),
        ('3', '2016'),
        ('4', '2015'),
        ('5', '2014'),
    ]
    # Month
    Month = [
        ('', 'Month'),
        ('	1	', '	Jan	'),
        ('	2	', '	Feb	'),
        ('	3	', '	Mar	'),
        ('	4	', '	Apr	'),
        ('	5	', '	May	'),
        ('	6	', '	Jun	'),
        ('	7	', '	Jul	'),
        ('	8	', '	Aug	'),
        ('	9	', '	Sep	'),
        ('	10	', '	Oct	'),
        ('	11	', '	Nov	'),
        ('	12	', '	Dec	'),
    ]

    Make = [
        ('', 'Brand'),
        ('1', 'Mercedes'),
        ('2', 'Audi'),
        ('3', 'BMW'),
        ('4', 'MiNi'),
        ('5', 'Volvo'),
        ('6', 'Roll Royce'),
        ('7', 'Lamborgini'),
        ('8', 'Ferrari'),
        ('9', 'Bugatti'),
        ('10', 'Aston Martin'),
        ('11', 'Land Rover'),
        ('12', 'Jaguar'),
        ('13', 'Porsche'),
        ('14', 'Maserati'),
        ('15', 'Bentley'),
    ]

    # Owner
    Owner = [
        ('', 'Owner'),
        ('1', 'First'),
        ('2', 'Second'),
        ('3', 'Third'),
        ('4', 'Company Owned'),
    ]

    # Make/Brand


    # km
    km = [
        ('', 'Km'),
        ('1', 'Below 10000'),
        ('2', '10000-25000'),
        ('3', '25000+')
    ]
    # Variants
    Variant = [
        ('', 'Variant'),
        ('1', 'Top-Diesel'),
        ('2', 'Top-Petrol'),
        ('3', 'Mi-Diesel'),
        ('4', 'Mi-Petrol'),
        ('5', 'Low-Diesel'),
        ('6', 'Low-Petrol'),
        ('7', 'Hybrid'),
    ]

    # Color
    Color = [
        ('', 'Color'),
        ('1', 'BEIG'),
        ('2', 'BLACK'),
        ('3', 'BLUE'),
        ('4', 'BRONZE'),
        ('5', 'BROWN'),
        ('6', 'GOLD'),
        ('7', 'GREEN'),
        ('8', 'GREY'),
        ('9', 'MAROON'),
        ('10', 'ORANGE'),
        ('11', 'PURPLE'),
        ('12', 'RED'),
        ('13', 'SILVER'),
        ('14', 'WHITE'),
        ('15', 'YELLOW'),
    ]

    # Fuel
    Fuel = [
        ('', 'Fuel'),
        ('1', 'Petrol'),
        ('2', 'Diesel'),
        ('3', 'Hybrid'),
        ('4', 'Electric'),
        ('5', 'Hydrogen'),
    ]
    # Use Type
    UseType = [
        ('', 'Use'),
        ('1', 'Personal'),
        ('2', 'Commercial'),
    ]

    # Insurance Type
    InsuranceType = [
        ('1', 'Comprehensive'),
        ('2', 'Third Party'),
        ('3', 'Expired'),
    ]
    # Accident,InsuranceClaimed,ServicefromAuthorisedDealer
    YesNo = [
        ('1', 'No'),
        ('2', 'Yes'),
    ]

    # Owners Profession
    # Owners Income

    # Alternate Fuel
    # Km/miles

    owner_name = models.CharField(max_length=50)
    owner_email = models.EmailField(max_length=200)
    owner_mobile = models.CharField(max_length=10)
    buy_year = models.CharField(choices= MFG_YR, max_length=200)
    veh_make_month = models.CharField(choices=Month, max_length=200)
    veh_owner = models.CharField(choices=Owner, max_length=200)
    veh_make = models.CharField(max_length=200, choices=Make)
    veh_km = models.CharField(choices=km, max_length=200)
    veh_variant = models.CharField(choices=Variant, max_length=200)
    veh_Color = models.CharField(choices=Color, max_length=200)
    veh_fuel = models.CharField(choices=Fuel, max_length=200)
    veh_usetype = models.CharField(choices=UseType, max_length=200)
    veh_Insurancetype = models.CharField(choices=InsuranceType, max_length=200, default='Comprehensive')
    veh_accident = models.CharField(max_length=200, choices=YesNo, default='No')
    veh_Insuranceclaimed = models.CharField(choices=YesNo, max_length=200, default='No')
    veh_Insuranceclaimamount = models.IntegerField(default=0)
    veh_servicehistory = models.CharField(max_length=200, choices=YesNo, default='No')
    veh_existingLoan = models.CharField(max_length=200, choices=YesNo, default='No')
    veh_image1 = models.FileField(null=True, blank=True, upload_to='photo')


    def __unicode__(self):
        return self.title

Pycharm/Dasmach/buysale/forms.py
# make sure this is at the top if it isn't already
from django import forms
from buysale.models import car,newsletter,contact
# our new form
class vehicle(forms.ModelForm):
    owner_name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Owner Name'}))
    owner_email = forms.EmailField(widget=forms.TextInput(attrs={'placeholder': 'Email ID'}))
    owner_mobile = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Contact No'}))
    class Meta:
        model = car
        fields = '__all__'

class contact(forms.ModelForm):
    contact_name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Owner Name', 'size': '49'}))
    contact_email = forms.EmailField(widget=forms.TextInput(attrs={'placeholder': 'Email ID', 'size': '49'}))
    contact_mobile = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Contact No', 'size': '49'}))
    contact_message = forms.CharField(widget=forms.Textarea(attrs={'placeholder': 'Your Message','rows':'7', 'cols':'48'}))
    class Meta:
        model = contact
        fields = '__all__'

class newsletter(forms.ModelForm):
    class Meta:
        model = newsletter
        fields = '__all__'

Pycharm/Dasmach/buysale/views.py
from django.shortcuts import render, redirect
from django.core.mail import send_mail
from buysale.forms    import vehicle,newsletter,contact
from django.http import JsonResponse
from django.contrib import messages

# Create your views here.
def index(request):
   if request.method=="POST":
        form = contact(request.POST)
        if form.is_valid():
            contact_item = form.save()
            contact_item.save()
   else:
        form = contact()
   return render(request, 'index.html', {'form':form})


def vup(request):
    if request.method == "POST":
        form = vehicle(request.POST, request.FILES)
        if form.is_valid():
            vehicle_item = form.save()
            vehicle_item.save()

    else:

        form = vehicle()
    return render(request, 'vehupl.html', {'form': form})


def catalogue(request):
    from buysale.models import car
    data = car.objects.all()
    car = {
        "vehicle": data
    }
    if request.method == "POST":
        form = newsletter(request.POST)
        if form.is_valid():
            newsletter_item = form.save()
            newsletter_item.save()
    else:
        form = newsletter()
    return render(request, 'products.html', car)


def single(request):
    return render(request, 'single.html')

Pycharm/Dasmach/buysale/templates/bicycles.html
<!--
Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE html>
<html>
<head>
<title>Bike Shop a Ecommerce Category Flat Bootstarp Responsive Website Template| Bicycles :: w3layouts</title>
<link href="css/bootstrap.css" rel='stylesheet' type='text/css' />
<!-- jQuery (Bootstrap's JavaScript plugins) -->
<script src="js/jquery.min.js"></script>
<!-- Custom Theme files -->
<link href="css/style.css" rel="stylesheet" type="text/css" media="all" />
<!-- Custom Theme files -->
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="Bike-shop Responsive web template, Bootstrap Web Templates, Flat Web Templates, Andriod Compatible web template, 
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<!--webfont-->
<link href='http://fonts.googleapis.com/css?family=Roboto:500,900,100,300,700,400' rel='stylesheet' type='text/css'>
<!--webfont-->
<!-- dropdown -->
<script src="js/jquery.easydropdown.js"></script>
<link href="css/nav.css" rel="stylesheet" type="text/css" media="all"/>
<script src="js/scripts.js" type="text/javascript"></script>
<!--js-->

</head>
<body>
<!--banner-->
<script src="js/responsiveslides.min.js"></script>
<script>  
    $(function () {
      $("#slider").responsiveSlides({
      	auto: false,
      	nav: true,
      	speed: 500,
        namespace: "callbacks",
        pager: true,
      });
    });
  </script>
<div class="banner-bg banner-sec">	
	  <div class="container">
			 <div class="header">
			       <div class="logo">
						 <a href="index.html"><img src="images/logo.png" alt=""/></a>
				   </div>							 
				  <div class="top-nav">										 
						<label class="mobile_menu" for="mobile_menu">
						<span>Menu</span>
						</label>
						<input id="mobile_menu" type="checkbox">
					   <ul class="nav">
						  <li class="dropdown1"><a href="bicycles.html">BICYCLES</a>
							  <ul class="dropdown2">
									<li><a href="bicycles.html">FIXED / SINGLE SPEED</a></li>
									<li><a href="bicycles.html">CITY BIKES</a></li>
									<li><a href="bicycles.html">PREMIMUN SERIES</a></li>												
							  </ul>
						  </li>
						  <li class="dropdown1"><a href="parts.html">PARTS</a>
							 <ul class="dropdown2">
									<li><a href="parts.html">CHAINS</a></li>
									<li><a href="parts.html">TUBES</a></li>
									<li><a href="parts.html">TIRES</a></li>
									<li><a href="parts.html">DISC BREAKS</a></li>
							  </ul>
						 </li>      
						 <li class="dropdown1"><a href="accessories.html">ACCESSORIES</a>
							 <ul class="dropdown2">
									<li><a href="accessories.html">LOCKS</a></li>
										<li><a href="accessories.html">HELMETS</a></li>
										<li><a href="accessories.html">ARM COVERS</a></li>
										<li><a href="accessories.html">JERSEYS</a></li>
							  </ul>
						 </li>               
						 <li class="dropdown1"><a href="404.html">EXTRAS</a>
							 <ul class="dropdown2">
									<li><a href="404.html">CLASSIC BELL</a></li>
									<li><a href="404.html">BOTTLE CAGE</a></li>
									<li><a href="404.html">TRUCK GRIP</a></li>
							  </ul>
						 </li>
						  <a class="shop" href="cart.html"><img src="images/cart.png" alt=""/></a>
					  </ul>
				 </div>
				 <div class="clearfix"></div>
			 </div>
	  </div> 				 
</div>
<!--/banner-->
<div class="bikes">		 
	 <div class="mountain-sec">
		 <h2>MOUNTAIN BIKES</h2>
		 <a href="single.html"><div class="bike">				 
			 <img src="images/bik3.jpg" alt=""/>
		     <div class="bike-cost">
					 <div class="bike-mdl">
						 <h4>NAME<span>Model:M4585</span></h4>
					 </div>
					 <div class="bike-cart">						 
						 <a class="buy" href="single.html">BUY NOW</a>
					 </div>
					 <div class="clearfix"></div>
				 </div>
				 <div class="fast-viw">
						<a href="single.html">Quick View</a>
				 </div>
			 </div></a>
			 <a href="single.html"><div class="bike">				 
				 <img src="images/bik1.jpg" alt=""/>
				 <div class="bike-cost">
					 <div class="bike-mdl">
						 <h4>NAME<span>Model:M4585</span></h4>
					 </div>
					 <div class="bike-cart">						 
						 <a class="buy" href="single.html">BUY NOW</a>
					 </div>
					 <div class="clearfix"></div>
				 </div>
				 <div class="fast-viw">
						<a href="single.html">Quick View</a>
				 </div>
			 </div></a>
			 <a href="single.html"><div class="bike none2">				 
				 <img src="images/bik4.jpg" alt=""/>
				 <div class="bike-cost">
					 <div class="bike-mdl">
						 <h4>NAME<span>Model:M4585</span></h4>
					 </div>
					 <div class="bike-cart">						 
						 <a class="buy" href="single.html">BUY NOW</a>
					 </div>
					 <div class="clearfix"></div>
				 </div>
				 <div class="fast-viw">
						<a href="single.html">Quick View</a>
				 </div>
			 </div></a>
			 <a href="single.html"><div class="bike none1">				 
				 <img src="images/bik6.jpg" alt=""/>
				 <div class="bike-cost">
					 <div class="bike-mdl">
						 <h4>NAME<span>Model:M4585</span></h4>
					 </div>
					 <div class="bike-cart">						 
						 <a class="buy" href="single.html">BUY NOW</a>
					 </div>
					 <div class="clearfix"></div>
				 </div>
				 <div class="fast-viw">
						<a href="single.html">Quick View</a>
				 </div>
			 </div></a>
			 <div class="clearfix"></div>
	  </div>
		 
	  <div class="singlespeed-sec">
		   <h2>SINGLE SPEED-BIKES</h2>
			 <a href="single.html"><div class="bike">				 
				 <img src="images/s1.jpg" alt=""/>
				 <div class="bike-cost">
					 <div class="bike-mdl">
						 <h4>NAME<span>Model:M4585</span></h4>
					 </div>
					 <div class="bike-cart">						 
						 <a class="buy" href="single.html">BUY NOW</a>
					 </div>
					 <div class="clearfix"></div>
				 </div>
				 <div class="fast-viw">
						<a href="single.html">Quick View</a>
				 </div>
			 </div></a>
			 <a href="single.html"><div class="bike">				 
				 <img src="images/s2.jpg" alt=""/>
				 <div class="bike-cost">
					 <div class="bike-mdl">
						 <h4>NAME<span>Model:M4585</span></h4>
					 </div>
					 <div class="bike-cart">						 
						 <a class="buy" href="single.html">BUY NOW</a>
					 </div>
					 <div class="clearfix"></div>
				 </div>
				 <div class="fast-viw">
						<a href="single.html">Quick View</a>
				 </div>
			 </div></a>
			 <a href="single.html"><div class="bike none2">				 
				 <img src="images/s3.jpg" alt=""/>
				 <div class="bike-cost">
					 <div class="bike-mdl">
						 <h4>NAME<span>Model:M4585</span></h4>
					 </div>
					 <div class="bike-cart">						 
						 <a class="buy" href="single.html">BUY NOW</a>
					 </div>
					 <div class="clearfix"></div>
				 </div>
				 <div class="fast-viw">
						<a href="single.html">Quick View</a>
				 </div>
			 </div></a>
			 <a href="single.html"><div class="bike none1">				 
				 <img src="images/s4.jpg" alt=""/>
				 <div class="bike-cost">
					 <div class="bike-mdl">
						 <h4>NAME<span>Model:M4585</span></h4>
					 </div>
					 <div class="bike-cart">						 
						 <a class="buy" href="single.html">BUY NOW</a>
					 </div>
					 <div class="clearfix"></div>
				 </div>
				 <div class="fast-viw">
						<a href="single.html">Quick View</a>
				 </div>
			 </div></a>
			 <div class="clearfix"></div>
		 </div>
		 
		 <div class="road-sec">
		   <h2>ROAD-BIKES</h2>
			 <a href="single.html"><div class="bike">				 
				 <img src="images/r1.jpg" alt=""/>
				 <div class="bike-cost">
					 <div class="bike-mdl">
						 <h4>NAME<span>Model:M4585</span></h4>
					 </div>
					 <div class="bike-cart">						 
						 <a class="buy" href="single.html">BUY NOW</a>
					 </div>
					 <div class="clearfix"></div>
				 </div>
				 <div class="fast-viw">
						<a href="single.html">Quick View</a>
				 </div>
			 </div></a>
			 <a href="single.html"><div class="bike">				 
				 <img src="images/r3.jpg" alt=""/>
				 <div class="bike-cost">
					 <div class="bike-mdl">
						 <h4>NAME<span>Model:M4585</span></h4>
					 </div>
					 <div class="bike-cart">						 
						 <a class="buy" href="single.html">BUY NOW</a>
					 </div>
					 <div class="clearfix"></div>
				 </div>
				 <div class="fast-viw">
						<a href="single.html">Quick View</a>
				 </div>
			 </div></a>
			 <a href="single.html"><div class="bike none2">				 
				 <img src="images/r2.jpg" alt=""/>
				 <div class="bike-cost">
					 <div class="bike-mdl">
						 <h4>NAME<span>Model:M4585</span></h4>
					 </div>
					 <div class="bike-cart">						 
						 <a class="buy" href="single.html">BUY NOW</a>
					 </div>
					 <div class="clearfix"></div>
				 </div>
				 <div class="fast-viw">
						<a href="single.html">Quick View</a>
				 </div>
			 </div></a>
			 <a href="single.html"><div class="bike none1">				 
				 <img src="images/r4.jpg" alt=""/>
				 <div class="bike-cost">
					 <div class="bike-mdl">
						 <h4>NAME<span>Model:M4585</span></h4>
					 </div>
					 <div class="bike-cart">						 
						 <a class="buy" href="single.html">BUY NOW</a>
					 </div>
					 <div class="clearfix"></div>
				 </div>
				 <div class="fast-viw">
						<a href="single.html">Quick View</a>
				 </div>
			 </div></a>
			 <div class="clearfix"></div>
		 </div>
		 
	 </div>
</div>
<!---->
<div class="footer">
	 <div class="container wrap">
		<div class="logo2">
			 <a href="index.html"><img src="images/logo2.png" alt=""/></a>
		</div>
		<div class="ftr-menu">
			 <ul>
				 <li><a href="bicycles.html">BICYCLES</a></li>
				 <li><a href="parts.html">PARTS</a></li>
				 <li><a href="accessories.html">ACCESSORIES</a></li>
				 <li><a href="404.html">EXTRAS</a></li>
			 </ul>
		</div>
		<div class="clearfix"></div>
	 </div>
</div>
<!---->

</body>
</html>


Pycharm/Dasmach/buysale/templates/cat_x.html
<!--
Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE html>
<html>
<head>
<title>Bike Shop a Ecommerce Category Flat Bootstarp Responsive Website Template| Cart :: w3layouts</title>
<link href="css/bootstrap.css" rel='stylesheet' type='text/css' />
<!-- jQuery (Bootstrap's JavaScript plugins) -->
<script src="js/jquery.min.js"></script>
<!-- Custom Theme files -->
<link href="css/form.css" rel="stylesheet" type="text/css" media="all" />
<link href="css/style.css" rel="stylesheet" type="text/css" media="all" />
<!-- Custom Theme files -->
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="bike Shop Responsive web template, Bootstrap Web Templates, Flat Web Templates, Andriod Compatible web template, 
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<!--webfont-->
<link href='http://fonts.googleapis.com/css?family=Roboto:500,900,100,300,700,400' rel='stylesheet' type='text/css'>
<!--webfont-->
<!-- dropdown -->
<script src="js/jquery.easydropdown.js"></script>
<link href="css/nav.css" rel="stylesheet" type="text/css" media="all"/>
<script src="js/scripts.js" type="text/javascript"></script>
<!--js-->

</head>
<body>
<!--banner-->
<script src="js/responsiveslides.min.js"></script>
<script>  
    $(function () {
      $("#slider").responsiveSlides({
      	auto: false,
      	nav: true,
      	speed: 500,
        namespace: "callbacks",
        pager: true,
      });
    });
  </script>
<div class="banner-bg banner-sec">
</div>
<!--/banner-->
<div class="cart">
	 <div class="container">
		 <div class="cart-top">
			<a href="index.html"><< home</a>
		 </div>	
			
		
</div>


</body>
</html>

Pycharm/Dasmach/buysale/templates/products.html
<!--A Design by W3layouts
Author: W3layout
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE html>
<html>
<head>
<title>DasMach</title>
	{% load staticfiles %}
<link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" type="text/css" media="all" />
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="static/js/jquery.min.js"></script>
<!-- Custom Theme files -->
<!--theme-style-->
<link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css" media="all" />
<!--//theme-style-->
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="Mattress Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template,
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<!--fonts-->
<link href='//fonts.googleapis.com/css?family=Lato:100,300,400,700,900' rel='stylesheet' type='text/css'>
<link href='//fonts.googleapis.com/css?family=Roboto:400,100,300,500,700,900' rel='stylesheet' type='text/css'><!--//fonts-->
<!-- start menu -->
<link href="{% static 'css/memenu.css' %}" rel="stylesheet" type="text/css" media="all" />
<script type="text/javascript" src="static/js/memenu.js"></script>
<script>$(document).ready(function(){$(".memenu").memenu();});</script>
<script src="static/js/simpleCart.min.js"> </script>
</head>
<body>
<!--header-->
<div class="header">
<!-- products -->
	<!-- grow -->
	<div class="grow">
		<div align ="right" class="container">
			<a class="color8" href="/">Home</a>
		</div>
	</div>
	<!-- grow -->
	<div class="pro-du">
		<div class="container">
			<div class="col-md-9 product1">
				<div class=" bottom-product">
					{% block content%}
							{% for veh in vehicle %}
					<div class="col-md-6 bottom-cd simpleCart_shelfItem">


						<div class="product-at ">
							<a href="/single"><img class="img-responsive" src="{{ veh.veh_image1.url }}" alt="" >
							<div class="pro-grid">
										<span class="buy-in">Buy Now</span>
							</div>
						</a>
						</div>

						<p class="tun"><span>{{ veh.get_veh_make_display }}</span><br>{{ veh.veh_Variant }}</p>


						<div class="ca-rt">
							<a href="#" class="item_add"><p class="number item_price"><i> </i>{{ veh.veh_price }}</p></a>
						</div>


						<div class="clearfix"></div>
					</div>

						{% endfor %}
				</div>


				</div>
			<div class="col-md-3 prod-rgt">
				<div class=" pro-tp">
					<div class="pl-lft">
						<a href="single.html"><img class="img-responsive" src="/static/images/l2.jpg" alt=""></a>
					</div>
					<div class="pl-rgt">
						<h6><a href="single.html">TRIBECA LIVING</a></h6>
						<p><a href="single.html">450$</a></p>
					</div>
						<div class="clearfix"></div>
				</div>
				<div class="pr-btm">
				<h4>What Our Client Say</h4>
					<img class="img-responsive" src="/static/images/pi.jpg" alt="">
					<h6>John</h6>
					<p>Lorem Ipsum is simply dummy text of the printing industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,</p>
				</div>
			</div>
				<div class="clearfix"></div>
		</div>
	</div>

	<!-- products -->
<div class="footer w3layouts">
				<div class="container">
			<div class="footer-top-at w3">

				<div class="col-md-3 amet-sed w3l">
				<h4>MORE INFO</h4>
				<ul class="nav-bottom">
						<li><a href="#">Book an Appointment</a></li>
						<li><a href="#">FAQ</a></li>
						<li><a href="contact.html">Location</a></li>
						<li><a href="#">Membership</a></li>
					</ul>
				</div>
				<div class="col-md-3 amet-sed w3ls">
					<h4>Styles</h4>
					<ul class="nav-bottom">
						<li><a href="#">Hatch</a></li>
						<li><a href="#">Sedan</a></li>
						<li><a href="#">SUV</a></li>
						<li><a href="#">Coupe</a></li>
						<li><a href="#">Convertible</a></li>
					</ul>

				</div>
{% endblock %}
			<!--	<div class="col-md-3 amet-sed agileits">
					<h4>NEWSLETTER</h4>
					<div class="stay agileinfo">
						<div class="stay-left wthree">

							<form action="" method="post" >{% csrf_token %}
						{{form.newsletter_email}}
							</form>
						</div>
						<div class="btn-1 w3-agileits">
							<form action="#" method="post">{% csrf_token %}

								<input type="submit" value="Subscribe">
							</form>
						</div>
							<div class="clearfix"> </div>
			</div>

				</div>-->
				<div class="col-md-3 amet-sed agileits-w3layouts">
				<h4>CONTACT US</h4>
					<p>Office: BTM Bangalore</p>
					<p>office : +91 8802545189</p>
				</div>
				<div class="clearfix"> </div>
			</div>
		</div>
		<div class="footer-class w3-agile">
		<p>© 2014 DasMach . All Rights Reserved   <a href="http://w3layouts.com/" target="_blank"></a> </p>
		</div>
		</div>
</div>
</body>
</html>